[project]
authors = ["Nikki Satmaka <30800020+NikkiSatmaka@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "idxmomentumbot"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.8,<3.13"
pandas = ">=2.2.3,<3"
scipy = ">=1.14.1,<2"
ta-lib = ">=0.5.1,<0.6"
ipykernel = ">=6.29.5,<7"
polars = ">=1.17.1,<2"
